version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 1
    target-branch: 'main'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    target-branch: 'main'
    allow:
      - dependency-name: 'synthetix'
        dependency-type: 'production'
